# Header
menu:
  #Home: /
  Archives: /archives/
  Tags: /tags/
  Timeline: /timeline/
  About: /about/
  # Favorite: /favorite/
  Github: https://github.com/MellongLau

# WeChat QrCode URL
wechat: blogImages/qrcode_for_mellong.jpg


# Content
excerpt_link: Read more
fancybox: true
profile: true
# Sidebar
sidebar: false
widgets:
- recent_posts
- links

thumbnail: false

# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:


# Contacts
contacts:
  github: http://github.com/MellongLau
  # weibo: http://weibo.com/panjiabang
  # twitter: https://twitter.com/_JamesPan_
  # linkedin: https://cn.linkedin.com/pub/jiabang-pan/50/bb4/86
  # telegram: https://telegram.me/jamespan
  rss: /atom.xml

#wechat: //i.imgur.com/JDKdlapm.jpg

# cnzz: 1000543904
recruit: false
default_thumbnail: //i.imgur.com/w2aNvOls.jpg
